name: Deploy

on:
  push:
    branches:
      - main
      - devlop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v4

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootJar -x test

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      # 4. Docker 이미지 빌드 & 저장
      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/carena-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/carena-api:latest


      # 5. EC2에서 Blue-Green 배포 실행
      - name: Blue-Green Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

            docker pull ${{ secrets.DOCKER_USERNAME }}/carena-api:latest

            # 현재 active 판단 (symlink 기준)
            ACTIVE=$(readlink nginx/conf.d/default.conf | grep -o 'blue\|green')

            if [ "$ACTIVE" = "blue" ]; then
              NEW="green"
              PORT=8081
            else
              NEW="blue"
              PORT=8082
            fi

            echo "현재 active: $ACTIVE"
            echo "새 배포 대상: $NEW"

            # 새 컨테이너 기동
            docker compose up -d $NEW

            # 헬스체크
            for i in {1..20}; do
              if curl -f http://localhost:${PORT}/actuator/health; then
                echo "헬스체크 성공"
                break
              fi
              sleep 3
            done

            # nginx 스위치 
            ln -sf nginx-${NEW}.conf nginx/conf.d/default.conf
            docker exec nginx nginx -s reload

            # 이전 컨테이너 종료
            if [ -n "$ACTIVE" ]; then
              docker stop $ACTIVE
            fi

            echo "✅ 배포 완료"